batch_size: 1
dual_model: False
logging_dir: './logs'
seed: 37
deterministic: False

data:
  path_to_dataset: './data/test'
  baseline: True
  save_interval: 10
  warmup_epochs: 10
  p_threshold: 0.5
  augmented_samples: 3
  augment_mu: 0.0
  augment_std: 1.0
  sharpening_temp: 0.5
  alpha: 0.5

model:
    embedding_dim: 64
    attn_dim: 512
    label_dim: 2

hydra:
  run:
    dir: .
  output_subdir: null