
epochs: 100
batch_size: 32
logging_dir: './logs'
seed: 37
deterministic: False

training:
  baseline: True
  save_interval: 10
  warmup_epochs: 10
  p_threshold: 0.5
  augmented_samples: 3
  augment_mu: 0.0
  augment_std: 1.0
  sharpening_temp: 0.5
  alpha: 0.5

data:
  path_to_training_set: './data/train'
  path_to_validation_set: './data/val'
  max_seq_len: 2580
  shuffle: True
  num_workers: 32
  pin_memory: False

model:
  embedding_dim: 64
  attn_dim: 512
  label_dim: 2

optimizer:
  lr: 0.001

hydra:
  run:
    dir: .
  output_subdir: null